name: 'Dev - PR Label Checker'
on:
  pull_request:
    branches:
      - dev
    types:
      - reopened
      - labeled
      - unlabeled
jobs:
  check_labels:
    name: 'Check PR Labels'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"
          message: "Please set a versioning label of either `major`, `minor`, or `patch` to the pull request."
          add_comment: true
  merge_pr:
    name: Merge PR
    needs:
      - check_labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5