name: 'Dev - PR Label Checker'
on:
  pull_request:
    branches:
      - dev
    types:
      - reopened
      - labeled
      - unlabeled
jobs:
  add_label:
    name: 'Set label auto-merge'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: auto-merge
  check_labels:
    name: 'Check PR Labels'
    needs:
      - add_label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"
          message: "Please set a versioning label of either `major`, `minor`, or `patch` to the pull request."
          add_comment: true